---
# tasks file for ansible-dcos-bootstrap-node

- name: Create genconf directory
  file: path={{ item }} state=directory mode=755
  with_items:
    - '{{ dcos_bootstrap_dir }}'
    - '{{ dcos_bootstrap_dir }}/genconf'

- name: Copy configuration file
  template: src=genconf/config.yaml.j2 dest={{ dcos_bootstrap_dir }}/genconf/config.yaml mode=755

- name: Copy ip-detect file
  template: src=genconf/ip-detect.j2 dest={{ dcos_bootstrap_dir }}/genconf/ip-detect mode=755

- name: Download the DC/OS installer
  get_url: url={{ dcos_bootstrap_generate_config_url }}/{{ dcos_bootstrap_generate_config }} dest={{ dcos_bootstrap_dir }}/{{ dcos_bootstrap_generate_config }} mode=755

- name: Add user to docker group
  user: name={{ ansible_user_id }} groups=docker append=yes
  become: true
  register: add_group

- name: Generate customized DC/OS build file
  command: '{{ dcos_bootstrap_dir }}/{{ dcos_bootstrap_generate_config }}'
  args:
    chdir: '{{ dcos_bootstrap_dir }}'

- name: Install docker-python
  yum: name=docker-python state=present
  become: true

- name: Host DC/OS install package through nginx Docker container
  docker:
    name: dcos-bootstrap
    image: nginx
    state: started
    ports:
      - '{{dcos_bootstrap_port}}:80'
    volumes:
      - '{{dcos_bootstrap_dir}}/genconf/serve:/usr/share/nginx/html:ro'
